


package net.strongdesign.stg;

import java.util.Set;

import lpsolve.LpSolveException;

/**
 * @author dominic.wist
 * 
 * There might be different strategies for checking CSC by using (I)LP
 *
 */
public interface ICSCCheckLPStrategy {
	
	
	/**
	 * Implements the linear programming CSC check according to Josep's Paper:
	 * Synthesis of Asynchronous Controllers Using Integer Linear Programming
	 * @param neededSignals - necessary signals for acting according to the specified I/O interface
	 * @return - true, if a solution was found, otherwise false
	 * @throws LpSolveException - can be thrown, if you work directly with the lpsolve java wrapper
	 */
	public boolean execute(Set<Integer> neededSignals) throws LpSolveException;
	
	
	/**
	 * Find signals s for which Cs v1 != Cs v2
	 * @param neededSignals - necessary signals for acting according to the specified I/O interface 
	 * and for CSC satisfaction 
	 * @return unbalanced signals w.r.t. lastResult (generated by execute(...))
	 */
	public Set<Integer> getUnbalancedSignals(Set<Integer> neededSignals);

}
