/* Generated By:JavaCC: Do not edit this line. HCExpressionParserConstants.java */
package net.strongdesign.balsa.hcexpressionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HCExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHANNEL = 3;
  /** RegularExpression Id. */
  int REQ = 4;
  /** RegularExpression Id. */
  int ACK = 5;
  /** RegularExpression Id. */
  int CONCUR = 6;
  /** RegularExpression Id. */
  int CHOICE = 7;
  /** RegularExpression Id. */
  int SEQUENCE = 8;
  /** RegularExpression Id. */
  int ENCLOSE = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int OPEN_B = 11;
  /** RegularExpression Id. */
  int CLOSE_B = 12;
  /** RegularExpression Id. */
  int EXPANSION = 13;
  /** RegularExpression Id. */
  int SHARP = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "<CHANNEL>",
    "<REQ>",
    "<ACK>",
    "\"||\"",
    "<CHOICE>",
    "\";\"",
    "\":\"",
    "\",\"",
    "<OPEN_B>",
    "<CLOSE_B>",
    "<EXPANSION>",
    "\"#\"",
    "\"+\"",
    "\"-\"",
    "\"set\"",
    "\"=\"",
    "\"\\n\"",
    "\"!\"",
    "\"?\"",
  };

}
