/* Generated By:JavaCC: Do not edit this line. HCExpressionParserConstants.java */
package net.strongdesign.balsa.hcexpressionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HCExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHANNEL = 3;
  /** RegularExpression Id. */
  int REQ = 4;
  /** RegularExpression Id. */
  int ACK = 5;
  /** RegularExpression Id. */
  int INP = 6;
  /** RegularExpression Id. */
  int OUTP = 7;
  /** RegularExpression Id. */
  int CONCUR = 8;
  /** RegularExpression Id. */
  int CHOICE = 9;
  /** RegularExpression Id. */
  int SEQUENCE = 10;
  /** RegularExpression Id. */
  int ENCLOSE = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int SYNCPROD = 14;
  /** RegularExpression Id. */
  int UP = 15;
  /** RegularExpression Id. */
  int DOWN = 16;
  /** RegularExpression Id. */
  int OPEN_B = 17;
  /** RegularExpression Id. */
  int CLOSE_B = 18;
  /** RegularExpression Id. */
  int EXPANSION = 19;
  /** RegularExpression Id. */
  int SHARP = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "<CHANNEL>",
    "<REQ>",
    "<ACK>",
    "<INP>",
    "<OUTP>",
    "\"||\"",
    "\"|\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"**\"",
    "\"up\"",
    "\"down\"",
    "<OPEN_B>",
    "<CLOSE_B>",
    "<EXPANSION>",
    "\"#\"",
    "\"+\"",
    "\"-\"",
    "\"\\n\"",
    "\"active\"",
    "\"passive\"",
    "\"scale\"",
    "\"scaled\"",
  };

}
